openapi: 3.0.0
info:
  title: Task and Workflow API
  description: API for managing tasks and workflows
  version: 1.0.0
paths:
  /task:
    get:
      summary: Get all tasks
      responses:
        '200':
          description: A list of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    workflow_id:
                      type: integer
                    createdAt:
                      type: string
                      format: date
                    updatedAt:
                      type: string
                      format: date
    post:
      summary: Create a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                workflow_id:
                  type: integer
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  workflow_id:
                    type: integer
                  createdAt:
                    type: string
                    format: date
                  updatedAt:
                    type: string
                    format: date


  /task/{id}:
    get:
      summary: Get a task by ID
      parameters:
        - name: id
          in: path
          required: true
          description: The task ID
          schema:
            type: integer
      responses:
        '200':
          description: Task details
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  workflow_id:
                    type: integer
                  createdAt:
                    type: string
                    format: date
                  updatedAt:
                    type: string
                    format: date
        '404':
          description: Task not found
    put:
      summary: Update a task by ID
      parameters:
        - name: id
          in: path
          required: true
          description: The task ID
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                workflow_id:
                  type: integer
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  workflow_id:
                    type: integer
                  createdAt:
                    type: string
                    format: date
                  updatedAt:
                    type: string
                    format: date
        '404':
          description: Task not found
    delete:
      summary: Delete a task by ID
      parameters:
        - name: id
          in: path
          required: true
          description: The task ID
          schema:
            type: integer
      responses:
        '200':
          description: Task deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Task not found

  /workflow:
    get:
      summary: Get all workflows
      responses:
        '200':
          description: A list of workflows
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    createdAt:
                      type: string
                      format: date
                    updatedAt:
                      type: string
                      format: date
    post:
      summary: Create a new workflow
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '201':
          description: Workflow created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  createdAt:
                    type: string
                    format: date
                  updatedAt:
                    type: string
                    format: date

  /workflow/{id}:
    get:
      summary: Get a workflow by ID
      parameters:
        - name: id
          in: path
          required: true
          description: The workflow ID
          schema:
            type: integer
      responses:
        '200':
          description: Workflow details
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  createdAt:
                    type: string
                    format: date
                  updatedAt:
                    type: string
                    format: date
        '404':
          description: Workflow not found
    put:
      summary: Update a workflow by ID
      parameters:
        - name: id
          in: path
          required: true
          description: The workflow ID
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        '200':
          description: Workflow updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  createdAt:
                    type: string
                    format: date
                  updatedAt:
                    type: string
                    format: date
        '404':
          description: Workflow not found
    delete:
      summary: Delete a workflow by ID
      parameters:
        - name: id
          in: path
          required: true
          description: The workflow ID
          schema:
            type: integer
      responses:
        '200':
          description: Workflow deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Workflow not found
